spring:
  application:
  name: abbank.service.customer
  datasource:
    url: jdbc:postgresql://host.docker.internal:5432/abbank
  #123
    username: myuser1
    password: 5432
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
server:
  port: 9090